[build]
buildCommand = "npm ci && npm run prisma:generate && npx prisma migrate deploy --schema src/database/schema.prisma && npm run build"

[deploy]
startCommand = "node dist/main.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 30

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PORT = "3000"
NODE_ENV = "production"
